### ISSUE TITLE
Missing Mysql Password

### ISSUE THREAD

**Issue by yaf** [ut7/piwik#1]
Au démarrage du container piwik-mysql, un soucis avec le mot de passe ROOT de mysql...

Prévoir l'execution d'une ligne genre:

``` bash
docker run -e MYSQL_ROOT_PQSSWORD=uberpass -name -piwik-mysql mysql:5.6
```

**Comment by etienneCharignon** [comment]
Après discussion avec Yannick je ferme car on ne veux pas passer le mot de passe ici
